name: mattermost_flutter
description: Mattermost Mobile with Flutter
version: 1.0.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path_provider: ^2.1.3
  image_picker: ^1.1.1
  webview_flutter: ^4.0.1
  shared_preferences: ^2.1.0
  http: ^1.1.1
  flutter_svg: ^2.0.10+1
  video_player: ^2.1.15
  connectivity_plus: ^6.0.3
  package_info_plus: ^8.0.0
  url_launcher: ^6.2.6
  provider: ^6.1.2
  file_picker: ^8.0.3
  permission_handler: ^11.3.1
  markdown: ^7.2.2
  flutter_markdown: ^0.7.1
  device_info_plus: ^10.1.0
  mime: ^1.0.5
  timezone: ^0.9.3
  archive: ^3.6.0
  path_to_regexp: ^0.4.0
  freezed_annotation: ^2.4.1
  background_fetch: ^1.3.4
  table_calendar: ^3.1.1
  video_thumbnail: ^0.5.3
  flutter_dotenv: ^5.1.0
  cached_network_image: ^3.3.1
  open_file: ^3.2.1
  keyboard_dismisser: ^3.0.0
  flutter_secure_storage: ^9.0.0
  flutter_math_fork: ^0.7.2
  flutter_local_notifications: ^17.1.2
  grouped_list: ^5.1.2
  share_plus: ^9.0.0
  flutter_vector_icons: ^2.0.0
  flutter_webrtc: ^0.10.3
  flutter_highlight: ^0.7.0
  pub_semver: ^2.1.4
  tinycolor2: ^3.0.1
  just_the_tooltip: ^0.0.12
  simple_tooltip: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.1.0
  build_runner: ^2.4.10
  freezed: ^2.5.2

flutter:
  uses-material-design: true
